apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-config
  namespace: microservice-app
data:
  USERS_API_ADDRESS: "http://users-api-service:8083"
  AUTH_API_ADDRESS: "http://auth-api-service:8000"
  TODOS_API_ADDRESS: "http://todos-api-service:8082"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_CHANNEL: "log_channel"
  TODOS_API_PORT: "8082"
  SERVER_PORT: "8083"
  AUTH_API_PORT: "8000"
  REDIS_ADDR: "redis-service.microservice-app.svc.cluster.local:6379"
  